#############################################################################
# Makefile for building: simpleEmailClient
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 12? 23 15:26:20 2016
# Project:  simpleEmailClient.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile simpleEmailClient.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = base64.cpp \
		cpop3.cpp \
		loginDialog.cpp \
		main.cpp \
		mainWidget.cpp moc_loginDialog.cpp \
		moc_mainWidget.cpp
OBJECTS       = base64.o \
		cpop3.o \
		loginDialog.o \
		main.o \
		mainWidget.o \
		moc_loginDialog.o \
		moc_mainWidget.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		simpleEmailClient.pro
QMAKE_TARGET  = simpleEmailClient
DESTDIR       = 
TARGET        = simpleEmailClient

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_loginDialog.h ui_mainWidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: simpleEmailClient.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile simpleEmailClient.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile simpleEmailClient.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/simpleEmailClient1.0.0 || $(MKDIR) .tmp/simpleEmailClient1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/simpleEmailClient1.0.0/ && $(COPY_FILE) --parents base64.h cpop3.h loginDialog.h main.h mainWidget.h .tmp/simpleEmailClient1.0.0/ && $(COPY_FILE) --parents base64.cpp cpop3.cpp loginDialog.cpp main.cpp mainWidget.cpp .tmp/simpleEmailClient1.0.0/ && $(COPY_FILE) --parents loginDialog.ui mainWidget.ui .tmp/simpleEmailClient1.0.0/ && (cd `dirname .tmp/simpleEmailClient1.0.0` && $(TAR) simpleEmailClient1.0.0.tar simpleEmailClient1.0.0 && $(COMPRESS) simpleEmailClient1.0.0.tar) && $(MOVE) `dirname .tmp/simpleEmailClient1.0.0`/simpleEmailClient1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/simpleEmailClient1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_loginDialog.cpp moc_mainWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_loginDialog.cpp moc_mainWidget.cpp
moc_loginDialog.cpp: ui_loginDialog.h \
		loginDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) loginDialog.h -o moc_loginDialog.cpp

moc_mainWidget.cpp: ui_mainWidget.h \
		mainWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainWidget.h -o moc_mainWidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_loginDialog.h ui_mainWidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_loginDialog.h ui_mainWidget.h
ui_loginDialog.h: loginDialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic loginDialog.ui -o ui_loginDialog.h

ui_mainWidget.h: mainWidget.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainWidget.ui -o ui_mainWidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

base64.o: base64.cpp base64.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o base64.o base64.cpp

cpop3.o: cpop3.cpp cpop3.h \
		base64.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cpop3.o cpop3.cpp

loginDialog.o: loginDialog.cpp loginDialog.h \
		ui_loginDialog.h \
		main.h \
		cpop3.h \
		base64.h \
		mainWidget.h \
		ui_mainWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginDialog.o loginDialog.cpp

main.o: main.cpp loginDialog.h \
		ui_loginDialog.h \
		cpop3.h \
		base64.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainWidget.o: mainWidget.cpp mainWidget.h \
		ui_mainWidget.h \
		main.h \
		cpop3.h \
		base64.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWidget.o mainWidget.cpp

moc_loginDialog.o: moc_loginDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginDialog.o moc_loginDialog.cpp

moc_mainWidget.o: moc_mainWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWidget.o moc_mainWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

