######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 23 15:26:17 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += base64.h cpop3.h loginDialog.h main.h mainWidget.h
FORMS += loginDialog.ui mainWidget.ui
SOURCES += base64.cpp cpop3.cpp loginDialog.cpp main.cpp mainWidget.cpp
